[build]
  publish = "dist"
  command = "npm run generate"
[build.environment]
  NODE_VERSION = "14"
  
[[plugins]]
  package = "netlify-plugin-submit-sitemap"
	[plugins.inputs]
	baseUrl = "https://loving-johnson-3ec336.netlify.app/"
	
	sitemapPath = "/sitemap.xml"
	providers = [
		"google",
		"bing",
		"yandex"
	]
	exclude = [
      		'**/**/admin',
	]
